import 'package:get/get.dart';

class MyLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en": {
          "1": "Hello",
          "Choose language": "Choose language",
          "Choose a profile type": "Choose a profile type",
          "Are you looking for services \n or providing them?":
              "Are you looking for services \n or providing them?",
          "Customer": "Customer",
          "Provider": "Provider",
          "Continue as Guest": "Continue as Guest",
          //home guest
          "Home": "Home",
          "Bookings": "Bookings",
          "Messages": "Messages",
          "Settings": "Settings",
          //sections
          "or select from sections": "or select from sections",
          "Hi!": "Hi!",
          "What service do \n you need?": "What service do \n you need?",
          "Get Started": "Get Started",
          //settings
          "Connect as Provider": "Connect as Provider",
          "Change Language": "Change Language",
          "Add Payment Card": "Add Payment Card",
          "Contact Us": "Contact Us",
          "Share Al3amel": "Share Al3amel",
          "Rate Us": "Rate Us",
          "Terms of Service": "Terms of Service",
          "Privacy Policy": "Privacy Policy",
          "FAQs": "FAQs",
          "About Us": "About Us",
          "Change Password": "Change Password",
          "Logout": "Logout",
          //services
          "Select service": "Select service",
          "services": "services",
          //provider account welecome
          "Welcome!": "Welcome!",
          "To create your provider account, please follow these steps:":
              "To create your provider account, please follow these steps:",
          "Fill in Personal Information": "Fill in Personal Information",
          "Provide your personal details for the account.":
              "Provide your personal details for the account.",
          "Create a Photo": "Create a Photo",
          "Upload a photo for your provider profile.":
              "Upload a photo for your provider profile.",
          "Choose Services": "Choose Services",
          "Select the services you will offer as a provider.":
              "Select the services you will offer as a provider.",
          "Get Started provider": "Get Started",
          // provider infos add
          "Provider Informations": "Provider Informations",
          "Arabic name": "Arabic name",
          "Name": "Name",
          "Whatsapp": "Whatsapp",
          "Website": "Website",
          "Save     ": "Save     ",
          "Please fill all fields.": "Please fill all fields.",
          "Provider Contacts": "Provider Contacts",
          "Phone": "Phone",
          "phone": "phone",
          "email": "Email",
          "Book Now": "Book Now",
          "This customer has not rated yet.":
              "This customer has not rated yet.",
          "No reviews currently": "No reviews currently",
          "Choose a photo \n from your gallery":
              "Choose a photo \n from your gallery",
          "Rating Only": "Rating Only",
          "Distance Only": "Distance Only",
          "Error": "Error",
          "Invalid OTP": "Invalid OTP",
          "Provider Sign In": "Provider Sign In",
          "Phone Number": "Phone Number",
          "Enter your phone number": "Enter your phone number",
          "Phone number is required": "Phone number is required",
          "Enter OTP received via SMS": "Enter OTP received via SMS",
          "OTP is required": "OTP is required",
          "Add your review": "Add your review",
          "Rating Dialog": "Rating Dialog",
          "Tap a star to set your rating. Add more description here if you want.":
              "Tap a star to set your rating. Add more description here if you want.",
          "Submit": "Submit",
          "Image Update": "Image Update",
          "The image has been updated successfully":
              "The image has been updated successfully",
          "SEND OTP": "SEND OTP",
          "OTP Verification": "OTP Verification",
          "We sent your code to +974 4455 ***":
              "We sent your code to +974 4455 ***",
          "Resend OTP Code": "Resend OTP Code",
          "This code will expired in ": "This code will expired in ",
          "booking": "booking",
          "Select a date": "Select a date",
          "Select your location": "Select your location",
          "Additional informatios": "Additional informatios",
          "Appartment": "Appartment",
          "Floor": "Floor",
          "House N°": "House N°",
          "Continue": "Continue",
          "The provider have accepted your demand":
              "The provider have accepted your demand",
          "The provider dosen't accept your demand":
              "The provider dosen't accept your demand",
          "You can Contact him": "You can Contact him",
          "Choose Another Provider": "Choose Another Provider",
          "You have new request": "You have new request",
          "Accept": "Accept",
          "Reject": "Reject",
          "Reason for Rejection": "Reason for Rejection",
          "Provider is fully booked with other demands.":
              "Provider is fully booked with other demands.",
          "Provider is on vacation/holiday": "Provider is on vacation/holiday",
          "Provider is unable to travel to the requested location":
              "Provider is unable to travel to the requested location",
          "Provider is experiencing technical difficulties":
              "Provider is experiencing technical difficulties",
          "Provider is currently unavailable":
              "Provider is currently unavailable",
          "Other reason": "Other reason",
          "If the response takes more than 30 minutes, you can cancel the request and choose a different service provider.":
              "If the response takes more than 30 minutes, you can cancel the request and choose a different service provider.",
          "Your request has been received successfully, and sent to the service provider \n You will receive a response very soon":
              "Your request has been received successfully, and sent to the service provider \n You will receive a response very soon",
          "All": "All",
          "Finished": "Finished",
          "Current": "Current",
          "Canceled": " Canceled ",
          "Pending": "Pending",
          "Problem Description": "Problem description",
          "Booking summary": "Booking summary",
          "Click to contact the provider": "Click to contact the provider",
          "Your demand has been accepted": "Your demand has been accepted",
          "you could leave your review": "you could leave your review",
          "Sign in": "Sign in",
          "Reset password": "Reset password",
          "Enter the email associated with your account and we'll send an email with instructions to reset your password.":
              "Enter the email associated with your account and we'll send an email with instructions to reset your password.",
          "your email": "your email",
          "Email address": "Email address",
          "Send Instructions": "Send Instructions",
          "Create new password": "Create new password",
          "Your new password must be different from previous used passwords.":
              "Your new password must be different from previous used passwords.",
          "Enter your new password": "Enter your new password",
          "Password": "Password",
          "Confirm password": "Confirm password",
          "Both passwords must match.": "Both passwords must match.",
          "Reset Password": "Reset Password",
          "Search service": "Search service",
          "Orders": "Orders",
          "Providers for": "Providers for ",
          "Booking": "Booking",
          "You are now in the process of booking the ":
              "You are now in the process of booking the ",
          " service, which will be performed by ":
              " service, which will be performed by ",
          "Today": "Today",
          "Tomorrow": "Tomorrow",
          "This week": "This week",
          "Next week": "Next week",
          "Next month": "Next month",
          "Pick a date": "Pick a date",
          "CurrentLocation": "Current",
          "Location:": "Location :",
          "Type here": "Type here",
          "Map": "Map",
          "Date": "Date",
          "Location": "Location ",
          "Service": "Service",
          "Go Home": "Go Home",
          "Problem description": "Problem description",
          "Services statistics": "Services statistics",
          "Completed successfuly": "Completed successfully",
          "In progression": "In progress",
          "Do you want exit ?": "Do you want exit ?",
          "Hey": "Hey",
          "Confirm": "Confirm",
          "Cancel": "Concel",
          "Complete": "Complete",
          "Rejected": "Rejected",
          "Completed": "Completed",
          "My orders": "My orders",
        },
        "ar": {
          "1": " اهلا ",
          "Choose language": "اختر اللغة",
          "Choose a profile type": "اختر نوع الملف الشخصي",
          "Are you looking for services \n or providing them?":
              "هل تبحث عن خدمات أم تقدمها؟",
          "Customer": "العميل",
          "Provider": "مقدم الخدمة",
          "Continue as Guest": "الاستمرار كضيف",
          //home guest
          "Home": "الرئيسية",
          "Bookings": "الحجوزات",
          "Messages": "الرسائل",
          "Settings": "الإعدادات",
          //sections
          "or select from sections": "أو حدد من الأقسام",
          "Hi!": "مرحبًا!",
          "What service do \n you need?": "ما الخدمة التي \n تحتاجها؟",
          "Get Started": "ابدأ",
          //settings
          "Connect as Provider": "تسجيل الدخول كمقدم خدمة",
          "Change Language": "تغيير اللغة",
          "Add Payment Card": "إضافة بطاقة دفع",
          "Contact Us": "اتصل بنا",
          "Share Al3amel": "مشاركة Al3amel",
          "Rate Us": "قيِّمنا",
          "Terms of Service": "شروط الخدمة",
          "Privacy Policy": "سياسة الخصوصية",
          "FAQs": "الأسئلة الشائعة",
          "About Us": "معلومات عنا",
          "Change Password": "تغيير كلمة المرور",
          "Logout": "تسجيل الخروج",
          //services
          "Select service": "اختر خدمة ",
          "services": "خدمات ",
          // provider account welcome
          "Welcome!": "أهلاً بك!",
          "To create your provider account, please follow these steps:":
              "لإنشاء حساب مقدم الخدمة الخاص بك، يرجى اتباع هذه الخطوات:",
          "Fill in Personal Information": "ملء المعلومات الشخصية",
          "Provide your personal details for the account.":
              "تقديم تفاصيلك الشخصية للحساب.",
          "Create a Photo": "إنشاء صورة",
          "Upload a photo for your provider profile.":
              "قم بتحميل صورة لملف مقدم الخدمة الخاص بك.",
          "Choose Services": "اختر الخدمات",
          "Select the services you will offer as a provider.":
              "حدد الخدمات التي ستقدمها كمقدم خدمة.",
          "Get Started provider": "ابدأ",
          // provider infos add
          "Provider Informations": "معلومات مقدم الخدمة",
          "Arabic name": "الاسم بالعربية",
          "Name": "الاسم",
          "Whatsapp": "واتساب",
          "Website": "الموقع الإلكتروني",
          "Save     ": "حفظ     ",
          "Please fill all fields.": "يرجى ملء جميع الحقول.",
          "Provider Contacts": "جهات اتصال مقدم الخدمة",
          "Phone": "الهاتف",
          "phone": "الهاتف",
          "email": "البريد الإلكتروني",
          "Book Now": "احجز الآن",
          "This customer has not rated yet.": "لم يتم تقييم هذا العميل بعد.",
          "No reviews currently": "لا توجد تقييمات حالياً",
          "Choose a photo \n from your gallery":
              "اختر صورة من معرض الصور الخاص بك",
          "Rating Only": "التقييم فقط",
          "Distance Only": "المسافة فقط",
          "Error": "خطأ",
          "Invalid OTP": "رمز OTP غير صحيح",
          "Provider Sign In": "تسجيل الدخول لمقدم الخدمة",
          "Phone Number": "رقم الهاتف",
          "Enter your phone number": "أدخل رقم هاتفك",
          "Phone number is required": "رقم الهاتف مطلوب",
          "Enter OTP received via SMS":
              "أدخل رمز OTP الذي تم استلامه عبر الرسائل النصية",
          "OTP is required": "رمز OTP مطلوب",
          "Add your review": "أضف تقييمك",
          "Rating Dialog": "مربع حوار التقييم",
          "Tap a star to set your rating. Add more description here if you want.":
              "اضغط على نجمة لتحديد تقييمك. يمكنك إضافة مزيد من الوصف هنا إذا رغبت.",
          "Submit": "إرسال",
          "Image Update": "تحديث الصورة",
          "The image has been updated successfully": "تم تحديث الصورة بنجاح",
          "SEND OTP": "إرسال رمز التحقق",
          "OTP Verification": "تحقق من رمز OTP",
          "We sent your code to +974 4455 ***":
              "لقد أرسلنا رمزك إلى +974 4455 ***",
          "Resend OTP Code": "إعادة إرسال رمز OTP",
          "This code will expired in ": "ستنتهي صلاحية هذا الرمز في",
          "booking": "الحجز",
          "Select a date": "حدد تاريخًا",
          "Select your location": "حدد موقعك",
          "Additional informatios": "معلومات إضافية",
          "Appartment": "شقة",
          "Floor": "الطابق",
          "House N°": "رقم المنزل",
          "Continue": "متابعة",
          "The provider have accepted your demand": "قد قبل مقدم الخدمة طلبك",
          "The provider dosen't accept your demand": "مقدم الخدمة لم يقبل طلبك",
          "You can Contact him": "يمكنك التواصل معه",
          "Choose Another Provider": "اختر مقدم خدمة آخر",
          "You have new request": "لديك طلب جديد",
          "Accept": "قبول",
          "Reject": "رفض",
          "Reason for Rejection": "سبب الرفض",
          "Provider is fully booked with other demands.":
              "مقدم الخدمة محجوز بالكامل مع طلبات أخرى.",
          "Provider is on vacation/holiday": "مقدم الخدمة في إجازة/عطلة",
          "Provider is unable to travel to the requested location":
              "مقدم الخدمة غير قادر على السفر إلى الموقع المطلوب",
          "Provider is experiencing technical difficulties":
              "مقدم الخدمة يواجه صعوبات تقنية",
          "Provider is currently unavailable": "مقدم الخدمة غير متوفر حاليًا",
          "Other reason": "سبب آخر",
          "If the response takes more than 30 minutes, you can cancel the request and choose a different service provider.":
              "إذا استغرق الرد أكثر من 30 دقيقة ، يمكنك إلغاء الطلب واختيار مزود خدمة آخر.",
          "Your request has been received successfully, and sent to the service provider \n You will receive a response very soon":
              "تم استلام طلبك بنجاح وتم إرساله إلى مقدم الخدمة \n ستتلقى إجابة قريبًا جداً",

          "All": "الكل",
          "Finished": "مكتمل",
          "Current": " قيد التنفيذ ",
          "Canceled": "ملغى",
          "Pending": " قيد الانتظار ",
          "Problem Description": "وصف المشكلة",
          "Booking summary": "ملخص الحجز",
          "Click to contact the provider": "انقر للتواصل مع مقدم الخدمة",
          "Your demand has been accepted": "تم قبول طلبك",
          "you could leave your review": "يمكنك ترك تقييمك",
          "Sign in": "تسجيل الدخول",
          "Reset password": "إعادة تعيين كلمة المرور",
          "Enter the email associated with your account and we'll send an email with instructions to reset your password.":
              "أدخل البريد الإلكتروني المرتبط بحسابك وسنرسل لك بريدًا إلكترونيًا يحتوي على تعليمات لإعادة تعيين كلمة المرور الخاصة بك.",
          "your email": "بريدك الإلكتروني",
          "Email address": "عنوان البريد الإلكتروني",
          "Send Instructions": "إرسال التعليمات",
          "Create new password": "إنشاء كلمة مرور جديدة",
          "Your new password must be different from previous used passwords.":
              "يجب أن تكون كلمة المرور الجديدة مختلفة عن كلمات المرور السابقة المستخدمة.",
          "Enter your new password": "أدخل كلمة المرور الجديدة",
          "Password": "كلمة المرور",
          "Confirm password": "تأكيد كلمة المرور",
          "Both passwords must match.": "يجب أن تتطابق كلمتي المرور.",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Search service": "ابحث عن خدمة",
          "Orders": "الطلبيات",
          "Providers for": "قائمة مقدمي خدمة ",
          "Booking": "الحجــز",
          "You are now in the process of booking the ":
              " أنت الآن في صدد حجز خدمة ",
          " service, which will be performed by ": "  والتي سيقدمها ",
          "Today": "اليوم",
          "Tomorrow": "غدًا",
          "This week": "هذا الأسبوع",
          "Next week": "الأسبوع القادم",
          "Next month": "الشهر القادم",
          "Pick a date": "اختر تاريخًا",
          "CurrentLocation": " الحالي",
          "Location:": "الموقع:",
          "Type here": "اكتب هنا",
          "Map": "الخريطة",
          "Date": "الموعد",
          "Location": " الموقع",
          "Service": "الخدمة",
          "Go Home": "الرئيسية",
          "Problem description": "توصيف المشكل",
          "Services statistics": "إحصائيات الخدمات",
          "Completed successfuly": "تم الانتهاء بنجاح",
          "In progression": "قيد التنفيذ",
          "Do you want exit ?": "هل تريد الخروج فعلا ؟",
          "Hey": "مرحبا",
          "Confirm": "تأكيد",
          "Cancel": "الغاء",
          "Complete": "أكمل",
          "Rejected": "ملغاة",
          "Completed": "مكتملة",
          "My orders": "طلبات العملاء",
        },
      };
}
